package:
  name: stress_tools
  # TODO: setup and use pyproject.toml and a Conda build Jinja template
  version: {{ VERSION }}

source:
  path: '..'

build:
  script:
    - mkdir build-package
    - cd build-package
    - cmake .. -DCMAKE_BUILD_TYPE=Release
    - cmake --build . --target stress_tools
    - cmake --install . --prefix ${PREFIX}
  ignore_run_exports:
    - python_abi

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake >=3.18
    - setuptools_scm >=6.2
    - eigen >=3.3.7
    - constitutive_tools
    - error_tools
    - vector_tools
    - boost >=1.59  # TODO: Separate the package/test configuration to make BOOST an optional build dependency
    - doxygen >=1.9  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  host:
    - boost >=1.59
    - eigen >=3.3.7
  run:
    - {{ compiler('cxx') }}
    - eigen >=3.3.7
    - constitutive_tools
    - error_tools
    - vector_tools

test:
  requires:
    - cmake >=3.18
    - boost >=1.59
    - doxygen  # TODO: Separate the package/documentation configuration to make Doxygen an optional build dependency
    - sphinx  # TODO: Separate the package/documentation configuration to make Sphinx an optional build dependency
  source_files:
    - CMakeLists.txt
    - src/cpp/tests/*
  commands:
    - mkdir build-tests
    - cd build-tests
    - cmake .. -DCMAKE_BUILD_TYPE=conda-test
    - cmake --build . --target all --verbose
    - ctest --output-on-failure
