name: environment
channels:
  - defaults
dependencies:
  - python>=3.7
  - boost>=1.53
  - breathe>=4.30.0
  - eigen>=3.3.7
  - pip
  - pytest
  - pytest-cov
  - sphinx>=3.0.4
  - sphinx_rtd_theme>=0.4.3
  - sphinxcontrib-bibtex
